colorMap = {
    'Fern': ,
    'MountainMeadow': ,
    'ChateauGreen': ,
    'PersianGreen': ,
    'PictonBlue': ,
    'Mariner': ,
    'CuriousBlue': ,
    'Denim': ,
    'Chambray': ,
    'Wisteria': ,
    'BlueGem': ,
    'Energy': ,
    'Turbo': ,
    'NeonCarrot': ,
    'Sun': '',
    'TerraCotta': '',
    'Valencia': '',
    'Cinnabar': '',
    'WellRead': '',
    'AlmondFrost': '',
    'WhiteSmoke': '',
    'Iron': '',
    'IronGray': '',
};